### ISSUE TITLE
App crashes when a new DataReader is received

### ISSUE THREAD

**Issue by EgorK0rshun** [superlistapp/super_native_extensions#309]
Personally, on two of my five devices the error is reproduced

[https://github.com/superlistapp/super_native_extensions/blob/67f062083c2158a1c4f62[…]1d7cc887a8/super_native_extensions/rust/src/clipboard_reader.rs](https://github.com/superlistapp/super_native_extensions/blob/67f062083c2158a1c4f62352a043411d7cc887a8/super_native_extensions/rust/src/clipboard_reader.rs#L36)

There are no `newClipboardReader` в Android part:
[https://github.com/superlistapp/super_native_extensions/tree/main/super_native_ext[…]ons/android/src/main/java/com/superlist/super_native_extensions](https://github.com/superlistapp/super_native_extensions/tree/main/super_native_extensions/android/src/main/java/com/superlist/super_native_extensions)

Logs:
```
F/libc  ( 6090): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 6170 (1.ui), pid 6090 (od.tracker.free)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/m01qser/m01q:12/SP1A.210812.016/M015FXXS5CWH1:user/release-keys'
Revision: '0'
ABI: 'arm'
Processor: '2'
Timestamp: 2024-02-06 17:04:40.475913920+0300
Process uptime: 150s
Cmdline: app
pid: 6090, tid: 6170, name: 1.ui >>> app <<<
uid: 10861
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
  r0 00000000 r1 00000001 r2 00000000 r3 acf3b4f0
  r4 92565558 r5 b8f40ec1 r6 adb88041 r7 00000000
  r8 ace87565 r9 b2ec0288 r10 b2ebff00 r11 af0f9788
  ip 00000000 sp af0f9770 lr ace91161 pc 92565558
backtrace:
   #00 pc 00065558 [anon:dart-code]
   #01 pc 001c615d /data/app/~~PMUCPy7YsEtK8cRxP4zJfg==app-Donw89GI5Mz5yynxQQ8XLg==/base.apk
   #02 pc 0006554e [anon:dart-code]
Lost connection to device.
the Dart compiler exited unexpectedly.
```

<img width="728" alt="Снимок экрана 2024-02-06 в 17 55 21" src="https://github.com/superlistapp/super_native_extensions/assets/120365747/5aa57d42-2680-407a-ac0b-587d47a2dad6">
<img width="695" alt="Снимок экрана 2024-02-06 в 17 55 40" src="https://github.com/superlistapp/super_native_extensions/assets/120365747/088cf849-be66-436f-9a68-31bc278a29fd">

**Comment by knopp** [comment]
What devices exactly are those? The stack trace does not show anything useful unfortunately likely because the binary is stripped. Also, are you able to reproduce this with `super_clipboard` example?

**Comment by knopp** [comment]
Also not sure what you mean by `newClipboardReader` android part. The part that handles method call is platform independent, it then calls the native platform code. If the code would missing it would not compile.

**Comment by EgorK0rshun** [comment]
Samsung Galaxy M01 and Samsung Galaxy A13 (13)

> What devices exactly are those?

**Comment by EgorK0rshun** [comment]
In the debug I caught the moment of the crash. The logs are uninformative because they are accessing a binary .so file.

> The stack trace does not show anything useful unfortunately

**Comment by EgorK0rshun** [comment]
Yes, I understand. Although it is difficult with Rust. But on other devices it works well, but on these two, which I wrote above, the null pointer crashes. Maybe there is a way to turn it into a check?

>  it then calls the native platform code

**Comment by knopp** [comment]
Both those devices are 32 bit arm. Can you confirm that the devices that are working are all arm64? There might be something wrong with the 32 bit arm slice.

**Comment by EgorK0rshun** [comment]
The problem is here

‘’’
"newClipboardReader" => {
    let reader = PlatformDataReader::new_clipboard_reader()?;
    Ok(Context::get()
        .data_reader_manager()
        .register_platform_reader(reader, call.isolate)
        .into())
}

‘’’

i think in https://doc.rust-lang.org/std/convert/trait.Into.html,

if return

‘’’

Ok(Value::Null)
‘’’
all will be fine

**Comment by EgorK0rshun** [comment]
in `register_platform_reader:`


```
let finalizable_handle = Arc::new(FinalizableHandle::new(32, isolate_id, move || {
    if let Some(manager) = weak_self.upgrade() {
        manager.readers.borrow_mut().remove(&id);
    }
}));
```
where isize: 32

**Comment by EgorK0rshun** [comment]
> i think in в https://doc.rust-lang.org/std/convert/trait.Into.html, 

because these methods work

```
let reader = PlatformDataReader::new_clipboard_reader()?;
let manager = Context::get().data_reader_manager();
let reader = manager.register_platform_reader(reader, call.isolate);

```

**Comment by EgorK0rshun** [comment]
in `register_platform_reader:`

```
let finalizable_handle = Arc::new(FinalizableHandle::new(32, isolate_id, move || {
    if let Some(manager) = weak_self.upgrade() {
        manager.readers.borrow_mut().remove(&id);
    }
}));
```
where isize: 32

**Comment by knopp** [comment]
> `Ok(Value::Null)` everything will be fine

It will not crash. But clipboard reading will not work anymore. 

I think armv7 is currently the only supported 32bit platform and I don't think I've tested in on a real device. This might be a pointer size issue somewhere in the FFI bindings. I'll try to get an armv7 device soon so that I can test this.

**Comment by EgorK0rshun** [comment]
Can you please tell me if the problem is something else? For example, in the [into() ](https://doc.rust-lang.org/std/convert/trait.Into.html)method? This is a very critical crash and I would like to work together to get rid of it as early as possible.

**Comment by knopp** [comment]
Unfortunately that's not really possible. I'd need to debug the crash locally with a symbolicated binary. It would help me if you gave me the exact models of the phones that you have, it's little bit tricky to find a 32bit-only android phone these days.

**Comment by EgorK0rshun** [comment]
> It would help me if you gave me the exact models of the phones that you have

![Screenshot_20240207_114330_Device Info](https://github.com/superlistapp/super_native_extensions/assets/120365747/03e741d7-d7ae-41d9-94d0-cce9286e0cae)
![Screenshot_20240207_111020](https://github.com/superlistapp/super_native_extensions/assets/120365747/1068e9e8-8327-4582-8336-9407204a2022)

**Comment by EgorK0rshun** [comment]
Samsung S5 mini, Android 6.0.1, catch error library not found,
32 Bit

```
11:23:50.073  I  [I] TIME: 2024-02-07T11:23:50.078562 Invalid argument(s): Failed to load dynamic library 'libsuper_native_extensions.so': dlopen failed: library "libsuper_native_extensions.so" not found:
                 #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
                 #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
                 #2      openNativeLibrary (package:super_native_extensions/src/native/context.dart:34:24)
                 #3      _getNativeContext (package:super_native_extensions/src/native/context.dart:12:19)
                 #4      _nativeContext (package:super_native_extensions/src/native/context.dart:20:24)
                 #5      _nativeContext (package:super_native_extensions/src/native/context.dart)
                 #6      superNativeExtensionsContext (package:super_native_extensions/src/native/context.dart:30:25)
                 #7      new ClipboardReaderImpl (package:super_native_extensions/src/native/clipboard_reader.dart:23:16)
                 #8      ClipboardReader.instance (package:super_native_extensions/src/clipboard_reader.dart:8:43)

```
<details><summary>device info</summary>
![Screenshot_20240207_113026](https://github.com/superlistapp/super_native_extensions/assets/120365747/1edce9ff-6afb-4fb9-841b-
b9463f172dbf)
</details>

**Comment by knopp** [comment]
Library not found means that the 32 bit arm (armeabi-v7a) dylib is not present in the final APK. Can you look inside the APK file to see which libraries are included for each platform?

**Comment by EgorK0rshun** [comment]
one more device has [ the same error](https://github.com/superlistapp/super_native_extensions/issues/309#issuecomment-1931548792)

![Screenshot 2024-02-07 at 13 35 51](https://github.com/superlistapp/super_native_extensions/assets/120365747/cfa091d3-3677-432f-b333-8f575f8f56a4)

**Comment by EgorK0rshun** [comment]
no.
> Is there any other error in device logs when this happens?

**Comment by knopp** [comment]
This actually seems like it might be a problem with dart ffi

https://github.com/simolus3/drift/issues/895

**Comment by EgorK0rshun** [comment]
ok, what should you do if this triggers your plugin?

**Comment by EgorK0rshun** [comment]
Error in iOS!
```
Invalid argument(s): Failed to lookup symbol 'super_native_extensions_init_message_channel_context': dlsym(RTLD_DEFAULT, super_native_extensions_init_message_channel_context): symbol not found
```

**Comment by knopp** [comment]
There might be something wrong with your iOS build. We have the plugin is deployed on many iOS devices without any issues. Are you able to reproduce this with a fresh flutter application?

**Comment by knopp** [comment]
As for the Android build, I'll try to reproduce this with an old android device, hopefully later today or tomorrow.

**Comment by EgorK0rshun** [comment]
Оk, thanks a lot!

>  I'll try to reproduce this with an old android device

I'll try to reproduce tomorrow, but the problem is observed only for the build from testflight, in debug everything is normal. It's strange and the log is
`Invalid argument(s): Failed to lookup symbol 'super_native_extensions_init_message_channel_context': dlsym(RTLD_DEFAULT, super_native_extensions_init_message_channel_context): symbol not found`
>  Are you able to reproduce this with a fresh flutter application?

**Comment by knopp** [comment]
I was able to reproduce the original bug (crash) on a 32bit android device. The problem is wrong argument type on one of the internal FFI methods. Should be fixed soon.

**Comment by EgorK0rshun** [comment]
glad to hear that, thank you!
> Should be fixed soon.

**Comment by EgorK0rshun** [comment]
as for iOS: still the same playback stacks as the cases for this crash.  Only it's an error that crashes, not a crash. The error crashes only in the release version. Testflight versions. It is not reproducible in debug. The error log is always the same. 
```
Invalid argument(s): Failed to lookup symbol 'super_native_extensions_init_message_channel_context': dlsym(RTLD_DEFAULT, super_native_extensions_init_message_channel_context): symbol not found
```

is displayed externally as the behavior for [this comment with s5,](https://github.com/superlistapp/super_native_extensions/issues/309#issuecomment-1931548792) when i can view the error. 
Please look at iOS too

**Comment by knopp** [comment]
The crash on 32bit android should be fixed in 0.8.5.

**Comment by knopp** [comment]
If you have problem with 0.8.5 other then the crash (i.e. library not found) please open that as new issue.

**Comment by EgorK0rshun** [comment]
Thanks a lot! 
Fixed it for my devices. I'm waiting for QA for the rest. I started it separately for iOS

**Comment by EgorK0rshun** [comment]
Thanks a lot! 
Fixed it for my devices. I'm waiting for QA for the rest. I started it separately for iOS
