### ISSUE TITLE
CargoKit Flutter 3.32

### ISSUE THREAD

**Issue by ihadabs** [superlistapp/super_native_extensions#524]
Flutter plugin not found, CargoKit plugin will not be applied.Flutter plugin not found, CargoKit plugin will not be applied.

**Comment by Miiite** [comment]
The above issue "description" means that you cannot run any android application, built with flutter `3.32.0` & a package that depends on super_native_extensions, because of an issue in CargoKit embedded in this package.

The linked issue gives a workaround, but it has to be implemented into this package, or you have to fork the library

**Comment by Adam-Langley** [comment]
Pubspec override to get moving until the PR is published to pub.dev

```
dependency_overrides:
  super_native_extensions:
    git:
      url: https://github.com/superlistapp/super_native_extensions.git
      ref: refs/pull/525/head
      path: super_native_extensions
```

**Comment by Adam-Langley** [comment]
Actually... scrub that - I am no longer confused.
I have removed all dependencies on the super_native_extensions (for the time being - commented out lots of code) - this CargoKit plugin is causing the breakage in path_provider_android.

So.. we're back to just trying to figure out this CargoKit issue. Argh.

**Comment by ilia-korolev** [comment]
This package definitely breaks platform dependent packages. It seems to use `plugin.gradle` from CargoKit twice, and the first time it runs without the fix. Not sure where this unmodified version comes from though

**Comment by Adam-Langley** [comment]
You're right. I can see the irondash_engine_context has also been pulled in - probably that needs to have the same patch.
I'll give that a try and report back.

**Comment by ilia-korolev** [comment]
Great catch!

I think in this case it should work as a quick workaround:

```yaml
dependency_overrides:
  super_native_extensions:
    git:
      url: https://github.com/superlistapp/super_native_extensions.git
      ref: refs/pull/525/head
      path: super_native_extensions
  irondash_engine_context:
    git:
      url: https://github.com/irondash/irondash.git
      ref: refs/pull/66/head
      path: engine_context/dart
```

**Comment by knopp** [comment]
Should be fixed in 0.9.0.

**Comment by Adam-Langley** [comment]
Hi @knopp please reopen as this doesn't fix it. 
I have upgraded package, flutter cleaned, run from cold boot - still get exactly the same error.

```
Connecting to VM Service at ws://127.0.0.1:64606/dlFHEgmmHfM=/ws
Connected to the VM Service.
I/risk.assessment( 4053): Compiler allocated 5250KB to compile void android.view.ViewRootImpl.performTraversals()
E/flutter ( 4053): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.path_provider_android.PathProviderApi.getExternalStoragePath"., null, null)
E/flutter ( 4053): #0      PathProviderApi.getExternalStoragePath (package:path_provider_android/messages.g.dart:196:7)
E/flutter ( 4053): <asynchronous suspension>
E/flutter ( 4053): #1      getExternalStorageDirectory (package:path_provider/path_provider.dart:154:24)
E/flutter ( 4053): <asynchronous suspension>
E/flutter ( 4053): #2      initializeLogger.<anonymous closure> (package:minrisk_assessment/drivers/logging.dart:16:53)
E/flutter ( 4053): <asynchronous suspension>
E/flutter ( 4053): #3      initializeLogger (package:minrisk_assessment/drivers/logging.dart:22:19)
E/flutter ( 4053): <asynchronous suspension>
E/flutter ( 4053): #4      main (package:minrisk_assessment/main.dart:59:3)
E/flutter ( 4053): <asynchronous suspension>
E/flutter ( 4053): 
```

To fix it, super_native_extensions also needs to update its reference to `irondash_engine_context` to point to the one which has been patched. The PR hasn't yet been accepted yet. Dont know why they're dragging their feet.

If I patch `super_native_extensions` 0.9.0 to point to:
```
  irondash_engine_context:
    git:
      url: https://github.com/irondash/irondash.git
      ref: refs/pull/66/head
      path: engine_context/dart
```

Then the issue is fixed.
